// This source generated by Dagger DotNet SDK. PLEASE DO NOT EDIT.
namespace {{ .Module }};

public static class Program
{
    public static async Task Main(string[] args)
    {
        await Entrypoint.Invoke(args);
    }
}
